server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
  mapper-locations: classpath:mapper/**/*.xml
spring:
  redis:
    host: 192.168.116.100
    port: 6379
    database: 0
    timeout: 1800000
    password: 3508539
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aug-oa?serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf-8
    username: root
    password: 3508539
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  activiti:
    database-schema-update: true
    db-history-used: true
    history-level: full
    check-process-definitions: true

wechat:
  mpAppId: wx8631b40050231f98
  mpAppSecret: 1351e7cec34430a1d3955e03858dae60
  userInfoUrl: http://oaaug.v5.idcfengye.com/admin/wechat/userInfo

